### ISSUE TITLE
Localied urls

### ISSUE THREAD

**Issue by rtpm** [psephopaiktes/astro-i18n-starter#2]
Hello, thank you for the great starter.

Is it possible somehow to localize slugs for pages when using src/pages/[lang]/contact.astro  so I can open the page with /en/contact and /de/kontakt somehow and both would use the same .astro file ?

Thanks

**Comment by psephopaiktes** [comment]
I think it's possible. By using [getStaticPaths()](https://docs.astro.build/en/guides/routing/#static-ssg-mode) within src/pages/[lang]/contact.astro, you can generate HTML for the contact page in each language from a single file.

You may want to refer to src/pages/[lang]/index.astro or src/pages/[lang]/404.astro as examples.

Here is a sample:

```src/pages/[lang]/contact.astro
---
import { localeParams, useTranslations, type Lang } from "@/i18n";
import Layout from "@/layouts/Base.astro";
const t = useTranslations(Astro.currentLocale as Lang);

const title = t({
  ja: "お問い合わせ",
  en: "Contact",
  "zh-cn": "联系我们",
  ar: "اتصل",
});

export const getStaticPaths = () => localeParams;
---

<Layout {title}>
    <h1>
      {title}
    </h1>

    <p>
      {
        t({
          ja: "お問い合わせはこちらから",
          en: "Contact us here",
          "zh-cn": "请通过此处联系我们",
          ar: "اتصل بنا هنا",
        })
      }
    </p>

    <form>...</form>
</Layout>
```
